
name: gestion_vente_ultra
description: Application mobile Android hors-ligne pour la gestion des ventes et du stock, avec sécurité, partage, multi-langue, et statistiques.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  uuid: ^4.4.0
  pdf: ^3.10.8
  printing: ^5.13.4
  file_picker: ^8.0.3
  open_filex: ^4.4.0
  intl: ^0.19.0
  fl_chart: ^0.66.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
